### ISSUE TITLE
执行不起来，是哪里有问题呢？

### ISSUE THREAD

**Issue by extrapeo** [zhongxintech/generator-web#8]
_

**Comment by extrapeo** [comment]
严重: Error deploying web application archive C:\Users\weilg\Downloads\apache-tomcat-7.0.76\apache-tomcat-7.0.76\webapps\generator-web-1.0.war
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/generator-web-1.0]]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:903)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1092)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1984)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by extrapeo** [comment]
找了一晚上 ，希望可以得到您的帮助

**Comment by Anspear** [comment]
你好，之前可能是因为打war包的时候打本地的那个jar包的时候出问题导致的，修改了一个地方，你更新下代码再试试。

**Comment by extrapeo** [comment]
嗯，已经解决了，maven仓库中引用的jar 和 本地的jar 冲突了应该是，解决jar包冲突之后就好了。感谢回复，哈哈。
